version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITUSER}
      RABBITMQ_DEFAULT_PASS: ${RABBITPASSWORD}
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
  go-app:
    build:
      context: .
      dockerfile: ./Docker/go/Dockerfile
    depends_on:
      - rabbitmq
      - mysql
    networks:
      - backend
    env_file:
      - .env
      
volumes:
  mysql_data:

networks:
  backend:
    driver: bridge